### ISSUE TITLE
Options not consistent for FS and S3FS in writeFile

### ISSUE THREAD

**Issue by vbudhram** [RiptideCloud/s3fs#17]
I was trying to specify the encoding type of the file to be written however I found that I could not use FS and S3FS interchangeably . 

The options for encoding in S3 putObject is 'ContentEncoding'. For FS it is 'encoding'.

Do you think there should be some options normalizing for these implementations?

**Comment by DavidTPate** [comment]
Yeah, I noticed some inconsistencies with the API in relation to this and was going to address thing. S3FS should be taking in the interface of FS and mapping it as needed.

I'll get this covered with 2.0.0.
