### ISSUE TITLE
temp file path get created inside s3 bucket when writing file stream

### ISSUE THREAD

**Issue by hfar** [RiptideCloud/s3fs#27]
Hi,

i am using the approach mentioned in below link : 
http://stackoverflow.com/questions/28018855/upload-a-file-to-amazon-s3-with-nodejs

but i have an issue when the file stream is uploaded to s3, the whole path of the temp file is getting created in `s3` bucket,for example : 

bucket  : `'My-Static-Assets/files/uploaded'`
the temp file path in Ubuntu server is : `'home/ubuntu/www/html/sampleProject/public/files/uploaded'`

The file is written to the following path in `s3` : 
`My-Static-Assets/files/uploaded/home/ubuntu/www/html/sampleProject/public/files/uploaded`
instead of : 
`My-Static-Assets/files/uploaded`
 
any idea why temp file path `'home/ubuntu/www/html/sampleProject/public/files/uploaded'` get created inside `s3` bucket when writing the file?

the issue didn't happen in localhost (windows) while it did happen in QA site (ubuntu).

thanks for your help.

**Comment by hfar** [comment]
i found the solution myself ,the file name i was sending to write file was wrong , i only replaced \ with / when getting the file name from temp path. 

var filePath= 'home\ubuntu\www\html\sampleProject\public\files\myfile.jpg'.replace(/\\/g, '/');

var fileName = filePath.substr(filePath.lastIndexOf('/')+1,filePath.length-1)

**Comment by DavidTPate** [comment]
Gotcha. Sounds like everything is working as expected, that's the result that I expect. Just so you don't have to use `lastIndexOf` and deal with different systems I would utilize [Path.parse()](https://nodejs.org/api/path.html#path_path_parse_pathstring) in Node.js.

**Comment by hfar** [comment]
Thanks David .. got it I am new in nodejs yes like you said I should use Path.parse :)

**Comment by DavidTPate** [comment]
No problem! We all are learning at some point. :+1:
